/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "customFields": {
    "bench_url": "https://tremor.licenser.net/bench"
  },
  "title": "Tremor",
  "tagline": "An early-stage event processing system for unstructured data with rich support for structural pattern-matching, filtering and transformation.",
  "url": "https://www.tremor.rs",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "favicon": "static/img/favicon.ico",
  "organizationName": "tremor-rs",
  "projectName": "tremor-rs/tremor-www",
  "staticDirectories": [
    "static"
  ],
  "plugins": [
    "/Users/jim/Desktop/github/tremor/node_modules/@cmfcmf/docusaurus-search-local/lib/server/index.js",
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "rfc",
        "path": "rfc",
        "routeBasePath": "rfc",
        "editUrl": "https://github.com/tremor-rs/tremor-www/tree/main/"
      }
    ],
  ],
  "presets": [
    [
      "redocusaurus",
      {
        "specs": [
          {
            "spec": "static/api/edge/openapi.yaml",
            "route": "/docs/edge/api"
          },
          {
            "spec": "static/api/v0.12/openapi.yaml",
            "route": "/docs/0.12/api"
          }
        ],
        "theme": {
          "primaryColor": "#1890ff"
        }
      }
    ],
    [
      "classic",
      {
        "debug": true,
        "docs": {
          "sidebarPath": "/Users/jim/Desktop/github/tremor/sidebars.js",
          "editUrl": "https://github.com/tremor-rs/tremor-www/tree/main/",
          "remarkPlugins": [
            null,
            null
          ],
          "lastVersion": "0.12",
          "versions": {
            "current": {
              "label": "edge",
              "path": "edge",
              "badge": true
            },
            "0.12": {
              "label": "0.12",
              "path": "0.12",
              "badge": true
            },
            "0.11": {
              "label": "0.11",
              "path": "0.11",
              "badge": true
            }
          }
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/tremor-rs/tremor-www/tree/main/"
        },
        "theme": {
          "customCss": "/Users/jim/Desktop/github/tremor/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "logo": {
        "alt": "Tremor Logo",
        "src": "img/tremor-logo.svg",
        "href": "https://www.tremor.rs/",
        "target": "_self"
      },
      "items": [
        {
          "type": "doc",
          "docId": "getting-started/index",
          "position": "left",
          "label": "Getting Started"
        },
        {
          "to": "blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "type": "dropdown",
          "label": "Docs",
          "positition": "left",
          "to": "docs/0.12",
          "items": [
            {
              "type": "doc",
              "docId": "guides/index",
              "label": "Guides"
            },
            {
              "type": "doc",
              "docId": "reference/index",
              "label": "Reference Documentation"
            },
            {
              "type": "doc",
              "docId": "api/index",
              "label": "API"
            }
          ],
          "position": "left"
        },
        {
          "type": "docsVersionDropdown",
          "position": "left",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://chat.tremor.rs",
          "className": "header-discord-link",
          "position": "right",
          "aria-label": "Community Chat"
        },
        {
          "href": "https://github.com/tremor-rs",
          "className": "header-github-link",
          "aria-label": "GitHub repository",
          "position": "right"
        },
        {
          "type": "search",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Social",
          "items": [
            {
              "label": "Discord",
              "href": "https://chat.tremor.rs/"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/TremorDEBS"
            }
          ]
        },
        {
          "title": "Media",
          "items": [
            {
              "label": "YouTube",
              "href": "https://www.youtube.com/channel/UCg1hxwEjh9szpYg8SxL0U7Q"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Code of Conduct",
              "to": "community/CodeofConduct"
            },
            {
              "label": "Download",
              "href": "https://github.com/tremor-rs/tremor-runtime/releases"
            }
          ]
        }
      ],
      "copyright": "\n          Copyright © 2025, Tremor Authors | Documentation Distributed under CC-BY-4.0.<br/><br>\n              <p style=\"font-size: smaller;\">Hosted by: <a href=\"https://www.netlify.com/\" rel=\"noreferrer noopener\" aria-label=\"Netlify\"><img src=\"/img/netlify-full-logo.svg\" alt=\"CNCF\" style=\"width: 3%;\" /></a>\n              &nbsp;&nbsp;&nbsp;&nbsp;\n              Project of: <a href=\"https://www.cncf.io/\" rel=\"noreferrer noopener\" aria-label=\"CNCF\"><img src=\"/img/cncf-color.svg\" alt=\"CNCF\" style=\"width: 5%;\" /></a></p>\n        <small>© 2025 The Linux Foundation. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our <a href=\"https://www.linuxfoundation.org/trademark-usage/\">Trademark Usage</a> page.</small>\n        "
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "tremor",
        "ebnf"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
